[pytest]
markers =
    create: test for POST
    delete: test for DELETE
    get: test for GET
    get_all: test for POST all
    patch: test for PATCH
    no_custom_id: do not require custom id
    custom_id: require custom id
