[pytest]
markers =
    create: test for POST
    delete_by_id: test for DELETE by id
    get_by_id: test for GET by id
    get_all: test for POST all
    patch_by_id: test for PATCH by id
    clear: test for clear DB after all other tests
