[pytest]
markers =
    create: test for POST
    delete_id: test for DELETE by id
    delete_last: test for DELETE by last id
    get_by_id: test for GET by id
    get_all: test for POST all
    patch: test for PATCH by id
    simple: simple tests
    clear: test for clear DB after all other tests
